#ifndef PINS_H
#define PINS_H

#define USART1_PORT GPIOA
#define USART1_TX_PIN GPIO9
#define USART1_RX_PIN GPIO10

#define BALANCE_PORT GPIOB
#define BALANCE_1_PIN GPIO7
#define BALANCE_2_PIN GPIO8
#define BALANCE_3_PIN GPIO9

#define LED_ON_PORT GPIOB
#define LED_ON_PIN GPIO4

#define LED_ACTIVE_PORT GPIOB
#define LED_ACTIVE_PIN GPIO5

#define LED_ERROR_PORT GPIOB
#define LED_ERROR_PIN GPIO6

#define VBATT_ADC_PORT GPIOA
#define VBATT_ADC_PIN GPIO0
#define VBATT_ADC_CH 0

#define VSOLAR_ADC_PORT GPIOA
#define VSOLAR_ADC_PIN GPIO1
#define VSOLAR_ADC_CH 1

#define SOLAR_CURRENT_ADC_PORT GPIOA
#define SOLAR_CURRENT_ADC_PIN GPIO2
#define SOLAR_CURRENT_ADC_CH 2

#define CELL_4V_ADC_PORT GPIOA
#define CELL_4V_ADC_PIN GPIO3
#define CELL_4V_ADC_CH 3

#define CELL_8V_ADC_PORT GPIOA
#define CELL_8V_ADC_PIN GPIO4
#define CELL_8V_ADC_CH 4

#define BB_SW_A_PORT GPIOA
#define BB_SW_A_PIN GPIO15

#define BB_D_A_PORT GPIOB
#define BB_D_A_PIN GPIO3

#define BB_SW_B_PORT GPIOB
#define BB_SW_B_PIN GPIO10

#define BB_D_B_PORT GPIOB
#define BB_D_B_PIN GPIO11


#endif
