#ifndef PINS_H
#define PINS_H

#define USART1_PORT GPIOA
#define USART1_TX_PIN GPIO9
#define USART1_RX_PIN GPIO10

#define BALANCE_PORT GPIOB
#define BALANCE_1_PIN GPIO7
#define BALANCE_2_PIN GPIO8
#define BALANCE_3_PIN GPIO9

#define LED_ON_PORT GPIOB
#define LED_ON_PIN GPIO4

#define LED_ACTIVE_PORT GPIOB
#define LED_ACTIVE_PIN GPIO5

#define LED_ERROR_PORT GPIOB
#define LED_ERROR_PIN GPIO6

#define VSOLAR_ADC_PORT GPIOA
#define VSOLAR_ADC_PIN GPIO0
#define VSOLAR_ADC_CH 0

#define VBATT_ADC_PORT GPIOA
#define VBATT_ADC_PIN GPIO1
#define VBATT_ADC_CH 1

#define SOLAR_CURRENT_ADC_PORT GPIOA
#define SOLAR_CURRENT_ADC_PIN GPIO2
#define SOLAR_CURRENT_ADC_CH 2

#define ADC_MULTIPLEX_PORT GPIOA
#define ADC_MULTIPLEX_CELL4V_PIN GPIO5
#define ADC_MULTIPLEX_CELL8V_PIN GPIO6
#define ADC_MULTIPLEX_VBATT_PIN GPIO7

#define SWITCH_PORT GPIOB
#define SWITCH_PIN GPIO0

#define DRIVERS_EN_PORT GPIOB
#define DRIVERS_EN_PIN GPIO1

#define BB_SW_A_PORT GPIOA
#define BB_SW_A_PIN GPIO15

#define BB_D_A_PORT GPIOB
#define BB_D_A_PIN GPIO3

#define BB_SW_B_PORT GPIOB
#define BB_SW_B_PIN GPIO10

#define BB_D_B_PORT GPIOB
#define BB_D_B_PIN GPIO11


#endif
